title = "Gourame"
theme = "hugo-story"

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
[Params]
  description = "Software development consultancy led by Ivan Sanchez"
  logo = "images/kyaw-tun-nI3bUW1Xqik-unsplash.jpeg"
  favicon = true

[Params.social]
  github = "https://github.com/s4nchez"
  twitter = "https://twitter.com/s4nchez"
  email = "ivan@gourame.com"
  linkedin = "https://www.linkedin.com/in/s4nchez/"
